"""
Simple Statistical Tests for Bit Sequences

Last modified: February 2025

Original version generated by ChatGPT-5
Adapted and extended by Prof. Miguel Vargas Martin

This program compares bit sequences produced by:
  1) a Large Language Model (LLM), and
  2) Python's `secrets` module (cryptographically secure PRNG).

The goal is NOT to prove randomness, but to illustrate how
simple statistical tests can reveal non-random structure.
"""

import secrets
import gzip

def load_bits_from_file(filename):
    """
    Load a sequence of bits from a text file.

    The file may contain arbitrary characters; only '0' and '1'
    are extracted. This allows students to paste raw LLM output
    without preprocessing.

    Args:
        filename (str): path to input file

    Returns:
        list[int]: list of bits (0s and 1s)
    """
    with open(filename, "r") as f:
        text = f.read()
    return [int(ch) for ch in text if ch in "01"]

def monobit_frequency(bits):
    """
    Compute the frequency of 1s and 0s (monobit test).

    For a random sequence, the fraction of 1s and 0s
    should be close to 0.5, but small deviations are expected
    for finite-length sequences.

    Args:
        bits (list[int]): input bit sequence
    Returns:
        tuple(float, float): (fraction_of_ones, fraction_of_zeros)
    """
    n = len(bits)
    ones = sum(bits)
    return ones / n, (n - ones) / n

def runs_count(bits):
    """
    Count the number of runs in the bit sequence.

    A run is a maximal subsequence of identical bits
    (e.g., 111 or 00). Too many or too few runs may
    indicate non-random structure.

    Args:
        bits (list[int]): input bit sequence
    Returns:
        int: number of runs
    """
    runs = 1
    for i in range(1, len(bits)):
        if bits[i] != bits[i - 1]:
            runs += 1
    return runs

def byte_diversity(bits):
    """
    Measure byte-level diversity.

    The bit sequence is grouped into 8-bit chunks and
    interpreted as bytes. We then count how many distinct
    byte values appear.

    For truly random data, most of the 256 possible byte
    values should occur when the sequence is long enough.

    Args:
        bits (list[int]): input bit sequence
    Returns:
        int: number of distinct byte values observed
    """
    byte_vals = [
        int("".join(map(str, bits[i:i + 8])), 2)
        for i in range(0, len(bits), 8)
    ]
    return len(set(byte_vals))

def gzip_compression_ratio(bits):
    """
    Estimate compressibility using gzip.

    Random data is largely incompressible, while structured
    or biased data tends to compress better.

    The ratio is:
        compressed_size / original_size

    Values closer to 1 indicate low compressibility and
    therefore higher apparent randomness.

    Args:
        bits (list[int]): input bit sequence
    Returns:
        float: gzip compression ratio
    """
    byte_vals = bytes(
        int("".join(map(str, bits[i:i + 8])), 2)
        for i in range(0, len(bits), 8)
    )
    original_size = len(byte_vals)
    compressed = gzip.compress(byte_vals)
    compressed_size = len(compressed)
    return compressed_size / original_size

# Data sources

# Load bits generated by an LLM (stored as text)
llm_bits = load_bits_from_file("llm_bits.txt")

# Generate 10,000 bits using a cryptographically secure PRNG
# 1250 bytes × 8 bits = 10,000 bits
seq_secrets = [
    int(b)
    for byte in secrets.token_bytes(1250)
    for b in f"{byte:08b}"
][:10000]

# Analysis and comparison
for name, seq in [("LLM", llm_bits), ("secrets", seq_secrets)]:
    ones_frac, zeros_frac = monobit_frequency(seq)
    runs = runs_count(seq)
    unique_bytes = byte_diversity(seq)
    ratio = gzip_compression_ratio(seq)

    print(f"=== {name} sequence ===")
    print(f"Length: \t\t\t\t{len(seq)} bits")
    print(f"Fraction of 1s: \t\t{ones_frac:.4f}")
    print(f"Runs: \t\t\t\t\t{runs}")
    print(f"Unique bytes: \t\t\t{unique_bytes}")
    print(f"Gzip compression ratio: \t{ratio:.3f}\n")

'''
=== LLM sequence ===
Length: 				10000 bits
Fraction of 1s: 		0.5000
Runs: 					5540
Unique bytes: 			230
Gzip compression ratio: 1.018

=== secrets sequence ===
Length: 				10000 bits
Fraction of 1s: 		0.4984
Runs: 					4941
Unique bytes: 			256
Gzip compression ratio: 1.018

The expected fraction of 1s in a random sequence is 0.5. While the 
LLM-generated sequence achieved perfect balance in this metric, it 
performed poorly on the others.

The expected number of runs is approximately n/2 (here, 5,000 for 
10,000 bits). The sequence generated by secrets exhibited a healthy 
level of alternation, whereas the LLM sequence showed reduced 
variability, indicating underlying structure.

For byte diversity, the ideal value is 256 (the full range of 
8-bit patterns). The secrets sequence reached this target, while the 
LLM sequence missed 26 distinct byte values, suggesting limited 
entropy.

The expected gzip compression ratio is around 1.0. Ratios higher 
than 1.0 indicate data that is effectively incompressible, aside 
from minor gzip metadata overhead.

In summary, an incautious practitioner might be misled if relying 
only on a few superficial randomness tests. Comprehensive 
evaluation across multiple metrics is essential to detect subtle 
patterns or biases. Cryptographic applications should always rely 
on cryptographically secure random generators (such as the secrets 
module in Python) rather than sequences produced by non-random 
sources like LLMs.
'''
