"""
Cryptographically Secure vs. Standard Randomness:
Timing and Bit Statistics

Last modified: February 2026
Author: Dr. Miguel Vargas Martin

This program compares randomness obtained from:
  1) os.urandom()  → cryptographically secure entropy source
  2) random.randint() → deterministic PRNG (Mersenne Twister)

The comparison is based on:
  - Average number of 1-bits in 128-bit values
  - Generation time
  - Compressibility of the generated byte streams
  - Visual inspection via scatter plots

⚠️ IMPORTANT:
- Passing simple statistical tests does NOT imply cryptographic security.
- The standard `random` module is NOT suitable for cryptography.
"""

import os
import random
import math
import time

# Bit statistics and timing (128-bit values)

iter = 15000                # Number of random samples
random.seed()               # Seed PRNG from system time (default behavior)

rand_crypto = b''           # Byte stream from os.urandom()
rand_strd = b''             # Byte stream from random.randint()

# --- Cryptographically secure random numbers ---
ones = 0                    # Total number of 1-bits observed
t = 0                       # Total time spent generating randomness

for i in range(iter):
    tt1 = time.perf_counter()
    iv = os.urandom(16)     # 16 bytes = 128 bits of cryptographic randomness
    tt2 = time.perf_counter()

    t += (tt2 - tt1)

    # Convert to integer for bit-level analysis
    serial = int.from_bytes(iv, byteorder="big")

    # Count number of 1s in the 128-bit value
    ones += bin(serial)[2:].count('1')

    # Accumulate raw bytes for compression testing
    rand_crypto += iv

print(
    "Avg # of 1's in {:,} 128-bit crypto random numbers: {:.3f}; "
    "time = {:.3f} ms".format(iter, ones / iter, 1000 * t)
)

# --- Standard PRNG (Mersenne Twister) ---
ones = 0
t = 0
val = math.pow(2, 128)       # Upper bound for 128-bit values

for i in range(iter):
    tt1 = time.perf_counter()
    iv = random.randint(0, val)
    tt2 = time.perf_counter()

    t += (tt2 - tt1)

    ones += bin(iv)[2:].count('1')

    # Store as fixed-length 16-byte value
    rand_strd += iv.to_bytes(16, byteorder='big')

print(
    "Avg # of 1's in {:,} 128-bit std random numbers: {:.3f}; "
    "time = {:.3f} ms".format(iter, ones / iter, 1000 * t)
)
